trigger:
  branches:
    include:
    - main
    - feature/*
    - development
    - dev

pr:
  branches:
    include:
    - main

resources:
  repositories:
  - repository: templates
    type: github
    name: vpapakir/iac-pipeline-templates
    ref: refs/heads/main
    endpoint: github-iac

variables:
- group: terraform
- group: shared

stages:
- template: azure/stages/infrastructure-pipeline.yml@templates
  parameters:
    ciTool: 'ado'
    terraformVersion: '1.14.0'
    workspacePrefix: 'azure-infra'
    terraformCloudToken: $(apiKey)
    azureCredentials:
      clientId: $(ARM_CLIENT_ID)
      clientSecret: $(ARM_CLIENT_SECRET)
      subscriptionId: $(ARM_SUBSCRIPTION_ID)
      tenantId: $(ARM_TENANT_ID)