trigger:
  branches:
    include:
    - main
    - feature/*
    - development
    - dev

pr:
  branches:
    include:
    - main

resources:
  repositories:
  - repository: templates
    type: github
    name: vpapakir/iac-pipeline-templates
    ref: refs/heads/main
    endpoint: github-iac

variables:
- group: terraform
- group: shared

stages:
- stage: Plan
  displayName: 'Plan Infrastructure'
  jobs:
  - job: PlanDev
    displayName: 'Plan Dev Environment'
    steps:
    - checkout: self
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '1.14.0'
    - script: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      displayName: 'Install Azure CLI'
    - script: |
        export TF_CLI_CONFIG_FILE=$(Agent.TempDirectory)/.terraformrc
        cat > $(Agent.TempDirectory)/.terraformrc << EOF
        credentials "app.terraform.io" {
          token = "$(apiKey)"
        }
        EOF
        terraform init -reconfigure
        terraform plan -detailed-exitcode
      displayName: 'Plan Dev'
      env:
        TF_WORKSPACE: azure-infra-dev
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
  
  - job: PlanStaging
    displayName: 'Plan Staging Environment'
    condition: false
    steps:
    - checkout: self
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '1.6.0'
    - script: |
        export TF_CLI_CONFIG_FILE=$(Agent.TempDirectory)/.terraformrc
        cat > $(Agent.TempDirectory)/.terraformrc << EOF
        credentials "app.terraform.io" {
          token = "$(apiKey)"
        }
        EOF
        terraform init
        terraform plan -var-file=environments/staging.tfvars
      displayName: 'Plan Staging'
      env:
        TF_WORKSPACE: azure-infra-staging
        TF_CLOUD_TOKEN: $(apiKey)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
  
  - job: PlanProd
    displayName: 'Plan Production Environment'
    condition: false
    steps:
    - checkout: self
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '1.6.0'
    - script: |
        export TF_CLI_CONFIG_FILE=$(Agent.TempDirectory)/.terraformrc
        cat > $(Agent.TempDirectory)/.terraformrc << EOF
        credentials "app.terraform.io" {
          token = "$(apiKey)"
        }
        EOF
        terraform init
        terraform plan -var-file=environments/prod.tfvars
      displayName: 'Plan Production'
      env:
        TF_WORKSPACE: azure-infra-prod
        TF_CLOUD_TOKEN: $(apiKey)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)

- stage: Dev
  displayName: 'Deploy to Development'
  dependsOn: Plan
  condition: and(succeeded(), contains(variables['Build.SourceVersionMessage'], '[apply]'))
  jobs:
  - job: DeployDev
    displayName: 'Apply Dev Environment'
    steps:
    - checkout: self
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '1.6.0'
    - script: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      displayName: 'Install Azure CLI'
    - script: |
        export TF_CLI_CONFIG_FILE=$(Agent.TempDirectory)/.terraformrc
        cat > $(Agent.TempDirectory)/.terraformrc << EOF
        credentials "app.terraform.io" {
          token = "$(apiKey)"
        }
        EOF
        terraform init
        terraform apply -auto-approve
      displayName: 'Apply Dev'
      env:
        TF_WORKSPACE: azure-infra-dev
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)

- stage: Staging
  displayName: 'Deploy to Staging'
  dependsOn: Dev
  condition: false
  jobs:
  - job: DeployStaging
    displayName: 'Apply Staging Environment'
    steps:
    - checkout: self
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '1.6.0'
    - script: |
        export TF_CLI_CONFIG_FILE=$(Agent.TempDirectory)/.terraformrc
        cat > $(Agent.TempDirectory)/.terraformrc << EOF
        credentials "app.terraform.io" {
          token = "$(apiKey)"
        }
        EOF
        terraform init
        terraform apply -var-file=environments/staging.tfvars -auto-approve
      displayName: 'Apply Staging'
      env:
        TF_WORKSPACE: azure-infra-staging
        TF_CLOUD_TOKEN: $(apiKey)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)

- stage: Prod
  displayName: 'Deploy to Production'
  dependsOn: Staging
  condition: false
  jobs:
  - deployment: DeployProd
    displayName: 'Apply Production Environment'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '1.6.0'
          - script: |
              export TF_CLI_CONFIG_FILE=$(Agent.TempDirectory)/.terraformrc
              cat > $(Agent.TempDirectory)/.terraformrc << EOF
              credentials "app.terraform.io" {
                token = "$(apiKey)"
              }
              EOF
              terraform init
              terraform apply -var-file=environments/prod.tfvars -auto-approve
            displayName: 'Apply Production'
            env:
              TF_WORKSPACE: azure-infra-prod
              TF_CLOUD_TOKEN: $(apiKey)
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)