name: Azure Infrastructure Pipeline

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

jobs:
  infrastructure:
    uses: vpapakir/iac-pipeline-templates/.github/workflows/infrastructure-pipeline.yml@main
    with:
      ci-tool: 'gh_actions'
      terraform-version: '1.6.0'
      workspace-prefix: 'azure-infra'
    secrets:
      terraform-cloud-token: ${{ secrets.TF_CLOUD_TOKEN }}